apiVersion: apps/v1
kind: Deployment
metadata:
  name: webdemo
spec:
  selector:
    matchLabels:
      app: webdemo
  replicas: 2
  template:
    metadata:
      labels:
        app: webdemo
    spec:
      volumes:
        - name: connectionstring
          hostPath:
            path: /var/data
      containers:
      - name: webdemo
        image: gsw/webdemo:v1.0.0
        imagePullPolicy: IfNotPresent #从本地镜像里拉取
        ports:
        - containerPort: 80
        volumeMounts:
          - name: connectionstring
            mountPath: /app/configuration
